version: '3.1'
services:
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - siec
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - siec   
      
      
  backend:
    build: ./backend
    ports:
      - 8080:8080
    networks:
      - siec
      
      
  frontend:
    build: ./frontend
    ports:
      - 8000:80
    depends_on: 
      - db
      - backend
    networks:
      - siec
    dns:
      - 8.8.8.8
  apache:
    image: httpd:latest
    ports:
      - "8081:80"
    volumes:
      - ./frontend/frontend:/usr/local/apache2/htdocs
    networks:
      - siec
volumes:
    db_data:
networks:
    siec:
